### ISSUE TITLE
Find out how to use Laravel's localization system in Lumen

### ISSUE THREAD

**Issue by belohlavek** [SPApawa/sistema-trabajos#18]
To avoid wasting time writing my own logic :)

**Comment by fedenaka** [comment]
This maybe? http://stackoverflow.com/questions/32630039/how-to-change-locale-language-on-lumen

**Comment by belohlavek** [comment]
Yep, but the idea is to use json files as a base, go through lumen's locale
system and make it available both as a resource (for react) and internally
for error messages and other needs.

**Comment by belohlavek** [comment]
The current plan is to use Lumen's translator as a central place to keep the one and only english version for the API errors.
The real locale for the app will be acceded in a separate resource. Closing this to separate it into two different issues.
