### ISSUE TITLE
[Easy] Evaluate replacing requests with arrays in all services

### ISSUE THREAD

**Issue by belohlavek** [SPApawa/sistema-trabajos#21]
I think it might make it easier to test in the future (arrays are easier to create on-the-fly).
On the other hand, maybe the parameters should be extracted from the request on the controller and passed individually to the service? Find out which option is better.

E.g.

`$this->service->doSomething($request->all());`

**vs**
```
$param1 = $request->input('param1');
//...
$this->service->doSomething($param1, $param2, $param3);
```

Recontra-re cc: @fedenaka

**Comment by fedenaka** [comment]
I think arrays intead of requests in the services its better because we need to know if a parameter is set or not, and if we extract the parameters on the controller we should add logic to the controller and we don't want that.

**Comment by belohlavek** [comment]
You should be able to extract the params and validate on the service though.
